version: 'latest'
services:

  flowfit-postgres:
    image: "postgres:latest"
    container_name: flowfit-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  flowfit-app:
    build: ./app
    container_name: flowfit-app
    environment:
      - DOCKER_LINK=${DOCKER_LINK}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TYPE=${DB_TYPE}
      - DB_DRIVER=${DB_DRIVER}
      - TYPE=${TYPE}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - 8080:8080
    links:
      - flowfit-postgres
    volumes:
      - ./app:/app

volumes:
  postgres-data: