version: 'latest'
services:

  flowfit-postgres:
    image: "postgres:latest"
    container_name: flowfit-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  flowfit-app:
    build: /app
    container_name: flowfit-app
    environment:
      - DB_SERVER=flowfit-postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    links:
      - flowfit-postgres
    volumes:
      - ./app:/app

volumes:
  postgres-data: